server {
    listen 80;                  # HTTP
    server_name localhost;

    location / {
        # 「/」にアクセスが来たら、標準のGrafanaコンテナに丸投げする
        proxy_pass http://grafana:3000;

        # クライアントの本来の情報をGrafanaに引き継ぐ設定
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}